

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - msgns-network

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - ./docker/postgres/.env
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres.rule=HostSNI(`postgres.localhost`)"
      - "traefik.tcp.routers.postgres.entrypoints=web"
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"
    networks:
      - msgns-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./docker/pgadmin/.env
    links:
      - postgres:db
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
    networks:
      - msgns-network

  denokv:
    image: ghcr.io/denoland/denokv
    container_name: denokv
    command: --sqlite-path /data/denokv.sqlite serve --access-token filocian_dev_123dev456
    env_file:
      - ./docker/denokv/.env
    volumes:
      - ./docker/denokv/data:/data
    ports:
      - "4512:4512"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.denokv.rule=Host(`denokv.localhost`)"
      - "traefik.http.services.denokv.loadbalancer.server.port=4512"
    networks:
      - msgns-network

  backend:
    build: 
      context: ./apps/backend
      dockerfile: ../../docker/backend/Dockerfile
    container_name: backend
    env_file:
      - ./docker/backend/.env
    volumes:
      - ./apps/backend:/app
    depends_on:
      - postgres
      - denokv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    networks:
      - msgns-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: ../../docker/frontend/Dockerfile
    container_name: frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"
    networks:
      - msgns-network

networks:
  msgns-network:
    driver: bridge
