

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - msgns-network

  db-global:
    image: postgres:latest
    container_name: db-global
    restart: always
    env_file:
      - ./docker/db-global/.env
    volumes:
      - ./docker/db-global/data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.db-global.rule=HostSNI(`db-global.localhost`)"
      - "traefik.tcp.routers.db-global.entrypoints=web"
      - "traefik.tcp.services.db-global.loadbalancer.server.port=5432"
    networks:
      - msgns-network

  db-eu:
    image: postgres:latest
    container_name: db-eu
    restart: always
    env_file:
      - ./docker/db-eu/.env
    volumes:
      - ./docker/db-eu/data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.db-eu.rule=HostSNI(`db-eu.localhost`)"
      - "traefik.tcp.routers.db-eu.entrypoints=web"
      - "traefik.tcp.services.db-eu.loadbalancer.server.port=5432"
    networks:
      - msgns-network

  db-us:
    image: postgres:latest
    container_name: db-us
    restart: always
    env_file:
      - ./docker/db-us/.env
    volumes:
      - ./docker/db-us/data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.db-us.rule=HostSNI(`db-us.localhost`)"
      - "traefik.tcp.routers.db-us.entrypoints=web"
      - "traefik.tcp.services.db-us.loadbalancer.server.port=5432"
    networks:
      - msgns-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./docker/pgadmin/.env
    environment:
      PGADMIN_SERVER_JSON_FILE: '/pgadmin4/servers.json'
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json:ro
    links:
      - db-global
      - db-eu
      - db-us
    depends_on:
      - db-global
      - db-eu
      - db-us
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
    networks:
      - msgns-network

  denokv:
    image: ghcr.io/denoland/denokv
    container_name: denokv
    command: --sqlite-path /data/denokv.sqlite serve --access-token filocian_dev_123dev456
    env_file:
      - ./docker/denokv/.env
    volumes:
      - ./docker/denokv/data:/data
    ports:
      - "4512:4512"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.denokv.rule=Host(`denokv.localhost`)"
      - "traefik.http.services.denokv.loadbalancer.server.port=4512"
    networks:
      - msgns-network

  backend:
    build: 
      context: ./apps/backend
      dockerfile: ../../docker/backend/Dockerfile
    container_name: backend
    env_file:
      - ./docker/backend/.env
    volumes:
      - ./apps/backend:/app
    depends_on:
      - db-global
      - denokv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    networks:
      - msgns-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: ../../docker/frontend/Dockerfile
    container_name: frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"
    networks:
      - msgns-network

networks:
  msgns-network:
    driver: bridge
