

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - msgns-network

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: filocian
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"
    networks:
      - msgns-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    links:
      - postgres:db
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.rg.local`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
    networks:
      - msgns-network

  denokv:
    image: denoland/deno:alpine
    container_name: denokv
    working_dir: /app
    command: "deno run --allow-net --allow-read --allow-write --unstable https://deno.land/x/denokv@0.2.0/server.ts"
    volumes:
      - ./docker/denokv/data:/app/data
    ports:
      - "4512:4512"
    networks:
      - msgns-network

  backend:
    build: 
      context: ./apps/backend
      dockerfile: ../../docker/backend/Dockerfile
    container_name: backend
    environment:
      - DB_HOST=postgres
      - DENO_KV_URL=http://denokv:4512
    depends_on:
      - postgres
      - denokv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.rg.local`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    networks:
      - msgns-network
    volumes:
      - ./apps/backend:/app

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: ../../docker/frontend/Dockerfile
    container_name: frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app.rg.local`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"
    networks:
      - msgns-network

networks:
  msgns-network:
    driver: bridge
